
version: '3' 

services:
  djangoserver:
    container_name: job_board                
    build: .                                    
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app 
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}  

 
  redis :
    image: redis:latest
    container_name: redis

  celery:
    container_name: celery
    build: .
    command: celery -A project worker -l INFO
    restart: always
    depends_on: 
      - redis
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"    
 