# Generated by Django 5.0.7 on 2024-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('GB', 'United Kingdom'), ('FR', 'France'), ('EG', 'Egypt'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('CN', 'China'), ('JP', 'Japan')], max_length=20, verbose_name='Select Country Job'),
        ),
    ]
