# Generated by Django 5.0.7 on 2024-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_applyed',
            field=models.IntegerField(default=0),
        ),
    ]
