# Generated by Django 5.0.7 on 2024-09-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_num_applyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('France', 'France'), ('Egypt', 'Egypt'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('China', 'China'), ('Japan', 'Japan')], max_length=20, verbose_name='Select Country Job'),
        ),
    ]
