# Generated by Django 5.0.2 on 2024-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
