# Generated by Django 5.0.2 on 2024-03-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply_apply_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='apply_at',
        ),
    ]
